In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\skme2\anaconda3\lib\site-packages (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\skme2\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\skme2\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\skme2\anaconda3\lib\site-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in c:\users\skme2\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

WARNING: Ignoring invalid distribution -atplotlib (c:\users\skme2\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\skme2\anaconda3\lib\site-packages)
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

C:\Users\skme2\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\skme2\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [3]:
# Series

In [4]:
books = ['c', 'c++', 'html', 'css', 'python', 'java', 'javascript']

In [5]:
type(books)

list

In [7]:
ser = pd.Series(data=books)

In [8]:
ser

0             c
1           c++
2          html
3           css
4        python
5          java
6    javascript
dtype: object

In [9]:
type(ser)

pandas.core.series.Series

In [11]:
ser[2]

'html'

In [13]:
ser[5]

'java'

In [16]:
ser[6]

'javascript'

In [19]:
ser.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [20]:
ser

a             c
b           c++
c          html
d           css
e        python
f          java
g    javascript
dtype: object

In [21]:
ser['d']

'css'

In [22]:
ser['e']

'python'

In [23]:
ser[4]

'python'

In [24]:
import numpy as np

In [156]:
arr = np.random.randint(10,100, size = (6,4))

In [157]:
arr

array([[71, 29, 91, 85],
       [92, 35, 90, 64],
       [24, 83, 13, 21],
       [26, 88, 73, 96],
       [93, 68, 99, 52],
       [61, 97, 47, 36]])

In [158]:
arr.ndim

2

In [159]:
df = pd.DataFrame(data=arr)

In [160]:
df

    0   1   2   3
0  71  29  91  85
1  92  35  90  64
2  24  83  13  21
3  26  88  73  96
4  93  68  99  52
5  61  97  47  36

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df.ndim

2

In [39]:
df[2]

0    53
1    38
2    82
3    64
4    13
5    66
Name: 2, dtype: int32

In [40]:
df

    0   1   2   3
0  90  98  53  31
1  19  26  38  25
2  59  84  82  76
3  40  41  64  89
4  79  10  13  56
5  94  29  66  20

In [49]:
type(df[0])

pandas.core.series.Series

In [48]:
type(df[3])

pandas.core.series.Series

In [47]:
df

    0   1   2   3
0  90  98  53  31
1  19  26  38  25
2  59  84  82  76
3  40  41  64  89
4  79  10  13  56
5  94  29  66  20

In [50]:
df

    0   1   2   3
0  90  98  53  31
1  19  26  38  25
2  59  84  82  76
3  40  41  64  89
4  79  10  13  56
5  94  29  66  20

In [161]:
df.columns = ['A', 'B', 'C', 'D']

In [162]:
df

    A   B   C   D
0  71  29  91  85
1  92  35  90  64
2  24  83  13  21
3  26  88  73  96
4  93  68  99  52
5  61  97  47  36

In [55]:
df['B']

0    98
1    26
2    84
3    41
4    10
5    29
Name: B, dtype: int32

In [56]:
df.shape

(6, 4)

In [57]:
df.size

24

In [58]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [59]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [61]:
df.head(2)

    A   B   C   D
0  90  98  53  31
1  19  26  38  25

In [85]:
df.tail(n = 3)

    A   B   C   D
3  40  41  64  89
4  79  10  13  56
5  94  29  66  20

In [86]:
df.sample(n = 4)

    A   B   C   D
1  19  26  38  25
4  79  10  13  56
3  40  41  64  89
5  94  29  66  20

In [87]:
df

    A   B   C   D
0  90  98  53  31
1  19  26  38  25
2  59  84  82  76
3  40  41  64  89
4  79  10  13  56
5  94  29  66  20

In [88]:
df['B']

0    98
1    26
2    84
3    41
4    10
5    29
Name: B, dtype: int32

In [89]:
df['A']

0    90
1    19
2    59
3    40
4    79
5    94
Name: A, dtype: int32

In [91]:
df[['A', 'B']]

    A   B
0  90  98
1  19  26
2  59  84
3  40  41
4  79  10
5  94  29

In [95]:
df[['B', 'C']]

    B   C
0  98  53
1  26  38
2  84  82
3  41  64
4  10  13
5  29  66

In [97]:
df[['C', "A", 'D']]

    C   A   D
0  53  90  31
1  38  19  25
2  82  59  76
3  64  40  89
4  13  79  56
5  66  94  20

In [98]:
df

    A   B   C   D
0  90  98  53  31
1  19  26  38  25
2  59  84  82  76
3  40  41  64  89
4  79  10  13  56
5  94  29  66  20

In [163]:
df['E'] = 25

In [164]:
df

    A   B   C   D   E
0  71  29  91  85  25
1  92  35  90  64  25
2  24  83  13  21  25
3  26  88  73  96  25
4  93  68  99  52  25
5  61  97  47  36  25

In [165]:
df['A+C'] = df['A'] + df['C']

In [166]:
df

    A   B   C   D   E  A+C
0  71  29  91  85  25  162
1  92  35  90  64  25  182
2  24  83  13  21  25   37
3  26  88  73  96  25   99
4  93  68  99  52  25  192
5  61  97  47  36  25  108

In [167]:
df['F'] = 23*12

In [168]:
df

    A   B   C   D   E  A+C    F
0  71  29  91  85  25  162  276
1  92  35  90  64  25  182  276
2  24  83  13  21  25   37  276
3  26  88  73  96  25   99  276
4  93  68  99  52  25  192  276
5  61  97  47  36  25  108  276

In [169]:
df['F*B'] = df['F']*df['B']

In [170]:
df

    A   B   C   D   E  A+C    F    F*B
0  71  29  91  85  25  162  276   8004
1  92  35  90  64  25  182  276   9660
2  24  83  13  21  25   37  276  22908
3  26  88  73  96  25   99  276  24288
4  93  68  99  52  25  192  276  18768
5  61  97  47  36  25  108  276  26772

In [171]:
df

    A   B   C   D   E  A+C    F    F*B
0  71  29  91  85  25  162  276   8004
1  92  35  90  64  25  182  276   9660
2  24  83  13  21  25   37  276  22908
3  26  88  73  96  25   99  276  24288
4  93  68  99  52  25  192  276  18768
5  61  97  47  36  25  108  276  26772

In [111]:
df.drop('A', axis=1)

    B   C   D   E  A+C    F    F*B
0  98  53  31  25  143  276  27048
1  26  38  25  25   57  276   7176
2  84  82  76  25  141  276  23184
3  41  64  89  25  104  276  11316
4  10  13  56  25   92  276   2760
5  29  66  20  25  160  276   8004

In [112]:
df

    A   B   C   D   E  A+C    F    F*B
0  90  98  53  31  25  143  276  27048
1  19  26  38  25  25   57  276   7176
2  59  84  82  76  25  141  276  23184
3  40  41  64  89  25  104  276  11316
4  79  10  13  56  25   92  276   2760
5  94  29  66  20  25  160  276   8004

In [118]:
df.index = "p q r s t u".split()

In [172]:
df

    A   B   C   D   E  A+C    F    F*B
0  71  29  91  85  25  162  276   8004
1  92  35  90  64  25  182  276   9660
2  24  83  13  21  25   37  276  22908
3  26  88  73  96  25   99  276  24288
4  93  68  99  52  25  192  276  18768
5  61  97  47  36  25  108  276  26772

In [121]:
df.drop(labels='B', axis=1)

    A   C   D   E  A+C    F    F*B
p  90  53  31  25  143  276  27048
q  19  38  25  25   57  276   7176
r  59  82  76  25  141  276  23184
s  40  64  89  25  104  276  11316
t  79  13  56  25   92  276   2760
u  94  66  20  25  160  276   8004

In [123]:
df.drop(columns="E")

    A   B   C   D  A+C    F    F*B
p  90  98  53  31  143  276  27048
q  19  26  38  25   57  276   7176
r  59  84  82  76  141  276  23184
s  40  41  64  89  104  276  11316
t  79  10  13  56   92  276   2760
u  94  29  66  20  160  276   8004

In [129]:
df.drop(columns='F')

    A   B   C   D   E  A+C    F*B
p  90  98  53  31  25  143  27048
q  19  26  38  25  25   57   7176
r  59  84  82  76  25  141  23184
s  40  41  64  89  25  104  11316
t  79  10  13  56  25   92   2760
u  94  29  66  20  25  160   8004

In [131]:
df.drop('p')

    A   B   C   D   E  A+C    F    F*B
q  19  26  38  25  25   57  276   7176
r  59  84  82  76  25  141  276  23184
s  40  41  64  89  25  104  276  11316
t  79  10  13  56  25   92  276   2760
u  94  29  66  20  25  160  276   8004

In [133]:
df.drop(labels='r')

    A   B   C   D   E  A+C    F    F*B
p  90  98  53  31  25  143  276  27048
q  19  26  38  25  25   57  276   7176
s  40  41  64  89  25  104  276  11316
t  79  10  13  56  25   92  276   2760
u  94  29  66  20  25  160  276   8004

In [138]:
df.drop(index='p', inplace=True)

In [139]:
df

    A   B   C   D   E  A+C    F    F*B
q  19  26  38  25  25   57  276   7176
r  59  84  82  76  25  141  276  23184
s  40  41  64  89  25  104  276  11316
t  79  10  13  56  25   92  276   2760
u  94  29  66  20  25  160  276   8004

In [143]:
df = df.drop(labels='A+C', axis=1)

In [144]:
df

    A   B   C   D   E    F    F*B
q  19  26  38  25  25  276   7176
r  59  84  82  76  25  276  23184
s  40  41  64  89  25  276  11316
t  79  10  13  56  25  276   2760
u  94  29  66  20  25  276   8004

In [148]:
df.drop(labels=['F*B', 'D', 'B'], axis=1, inplace=True)

In [149]:
df

    A   C   E    F
q  19  38  25  276
r  59  82  25  276
s  40  64  25  276
t  79  13  25  276
u  94  66  25  276

In [151]:
df = df.drop(labels=['r', 't', 's'])

In [152]:
df

    A   C   E    F
q  19  38  25  276
u  94  66  25  276

In [153]:
# Indexing/Extracting Data

In [154]:
df

    A   C   E    F
q  19  38  25  276
u  94  66  25  276

In [155]:
df

    A   C   E    F
q  19  38  25  276
u  94  66  25  276

In [173]:
df

    A   B   C   D   E  A+C    F    F*B
0  71  29  91  85  25  162  276   8004
1  92  35  90  64  25  182  276   9660
2  24  83  13  21  25   37  276  22908
3  26  88  73  96  25   99  276  24288
4  93  68  99  52  25  192  276  18768
5  61  97  47  36  25  108  276  26772

In [176]:
df.index = "p q r s t u".split()

In [177]:
df

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768
u  61  97  47  36  25  108  276  26772

In [178]:
df

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768
u  61  97  47  36  25  108  276  26772

In [180]:
df['B']

p    29
q    35
r    83
s    88
t    68
u    97
Name: B, dtype: int32

In [184]:
df.iloc[2]

A         24
B         83
C         13
D         21
E         25
A+C       37
F        276
F*B    22908
Name: r, dtype: int64

In [187]:
df.loc['r']

A         24
B         83
C         13
D         21
E         25
A+C       37
F        276
F*B    22908
Name: r, dtype: int64

In [188]:
df

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768
u  61  97  47  36  25  108  276  26772

In [189]:
df.iloc[0]

A        71
B        29
C        91
D        85
E        25
A+C     162
F       276
F*B    8004
Name: p, dtype: int64

In [190]:
df

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768
u  61  97  47  36  25  108  276  26772

In [192]:
df.iloc[1:3][['C','D']]

    C   D
q  90  64
r  13  21

In [197]:
df.iloc[2:5][['A','B']]

    A   B
r  24  83
s  26  88
t  93  68

In [200]:
df.iloc[-2:][['F', 'F*B']]

     F    F*B
t  276  18768
u  276  26772

In [203]:
df.iloc[-2:, -2:]

     F    F*B
t  276  18768
u  276  26772

In [207]:
df.iloc[2:4,2:4]

    C   D
r  13  21
s  73  96

In [208]:
# Masking : boolean Indexing

In [209]:
df

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768
u  61  97  47  36  25  108  276  26772

In [210]:
df

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768
u  61  97  47  36  25  108  276  26772

In [212]:
mask = df>30

In [213]:
mask

       A      B      C      D      E   A+C     F   F*B
p   True  False   True   True  False  True  True  True
q   True   True   True   True  False  True  True  True
r  False   True  False  False  False  True  True  True
s  False   True   True   True  False  True  True  True
t   True   True   True   True  False  True  True  True
u   True   True   True   True  False  True  True  True

In [214]:
df[mask]

      A     B     C     D   E  A+C    F    F*B
p  71.0   NaN  91.0  85.0 NaN  162  276   8004
q  92.0  35.0  90.0  64.0 NaN  182  276   9660
r   NaN  83.0   NaN   NaN NaN   37  276  22908
s   NaN  88.0  73.0  96.0 NaN   99  276  24288
t  93.0  68.0  99.0  52.0 NaN  192  276  18768
u  61.0  97.0  47.0  36.0 NaN  108  276  26772

In [216]:
df[df>50]

      A     B     C     D   E    A+C    F    F*B
p  71.0   NaN  91.0  85.0 NaN  162.0  276   8004
q  92.0   NaN  90.0  64.0 NaN  182.0  276   9660
r   NaN  83.0   NaN   NaN NaN    NaN  276  22908
s   NaN  88.0  73.0  96.0 NaN   99.0  276  24288
t  93.0  68.0  99.0  52.0 NaN  192.0  276  18768
u  61.0  97.0   NaN   NaN NaN  108.0  276  26772

In [221]:
df[~(df>50)]

      A     B     C     D   E   A+C   F  F*B
p   NaN  29.0   NaN   NaN  25   NaN NaN  NaN
q   NaN  35.0   NaN   NaN  25   NaN NaN  NaN
r  24.0   NaN  13.0  21.0  25  37.0 NaN  NaN
s  26.0   NaN   NaN   NaN  25   NaN NaN  NaN
t   NaN   NaN   NaN   NaN  25   NaN NaN  NaN
u   NaN   NaN  47.0  36.0  25   NaN NaN  NaN

In [225]:
df[~(df['B']>40)]

    A   B   C   D   E  A+C    F   F*B
p  71  29  91  85  25  162  276  8004
q  92  35  90  64  25  182  276  9660

In [231]:
df[df['B']>50][['C', 'D']]

    C   D
r  13  21
s  73  96
t  99  52
u  47  36

In [237]:
df[df['A']>40][['F', 'B']]

     F   B
p  276  29
q  276  35
t  276  68
u  276  97

In [240]:
df[df['D']<50]

    A   B   C   D   E  A+C    F    F*B
r  24  83  13  21  25   37  276  22908
u  61  97  47  36  25  108  276  26772

In [241]:
df[~(df['D']<50)]

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768

In [243]:
df['A']>40

p     True
q     True
r    False
s    False
t     True
u     True
Name: A, dtype: bool

In [245]:
df['D']<50

p    False
q    False
r     True
s    False
t    False
u     True
Name: D, dtype: bool

In [247]:
df[(df['A']>40) & (df['D']<50)]

    A   B   C   D   E  A+C    F    F*B
u  61  97  47  36  25  108  276  26772

In [248]:
df[~((df['A']>40) & (df['D']<50))]

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768

In [249]:
df

    A   B   C   D   E  A+C    F    F*B
p  71  29  91  85  25  162  276   8004
q  92  35  90  64  25  182  276   9660
r  24  83  13  21  25   37  276  22908
s  26  88  73  96  25   99  276  24288
t  93  68  99  52  25  192  276  18768
u  61  97  47  36  25  108  276  26772

In [252]:
arr = df.values

In [253]:
arr

array([[   71,    29,    91,    85,    25,   162,   276,  8004],
       [   92,    35,    90,    64,    25,   182,   276,  9660],
       [   24,    83,    13,    21,    25,    37,   276, 22908],
       [   26,    88,    73,    96,    25,    99,   276, 24288],
       [   93,    68,    99,    52,    25,   192,   276, 18768],
       [   61,    97,    47,    36,    25,   108,   276, 26772]],
      dtype=int64)

In [254]:
# Iris dataSet

In [255]:
import pandas as pd
import numpy as np

In [257]:
df = pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")

In [258]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [259]:
ls

 Volume in drive C is OS
 Volume Serial Number is 0CC1-C20F

 Directory of C:\Users\skme2\Downloads

07-09-2024  13:12    <DIR>          .
28-08-2024  09:30    <DIR>          ..
07-09-2024  11:58    <DIR>          .ipynb_checkpoints
01-06-2024  17:40               346 01_06_02.sql
01-06-2024  20:07               347 01_06_02_practice.sql
01-06-2024  16:43             8,550 01_06_window.sql
06-11-2023  11:20             2,633 01_11_sql_practice.sql
30-08-2024  08:26            15,553 01_inheritance_polymorphism_30_08.ipynb
07-09-2024  10:09            10,656 01_Text_Gen_project2_07_09.ipynb
03-05-2024  20:46         3,932,766 02_05_open_cv.ipynb
30-08-2024  11:08            58,925 02_Intermediate_python_30_08.ipynb
07-09-2024  11:58            74,959 02_numpy_07_09.ipynb
02-11-2022  15:49           410,816 0211resume.pdf
03-05-2024  20:45             4,167 03_05_cv2.ipynb
03-05-2024  19:04               576 03_05_open_cv.ipynb
04-06-2024  11:16           224,228 03_06_matplotlib_11_1230.ipynb
13-10-2023  15:25    <DIR>          03_10_4pm
13-10-2023  15:24        98,232,624 03_10_4pm.zip
07-09-2024  13:12           169,773 03_Pandas_07_09.ipynb
30-08-2024  16:39            19,703 03_Project_1_30_08.ipynb
04-06-2024  13:38            13,373 04_06_1230_01.xlsx
04-06-2024  12:48           570,133 04_06_matplotlib_11_1230.ipynb
04-06-2024  10:56            19,751 04_06_Python Basic_0930_11.ipynb
13-10-2023  15:24    <DIR>          04_10_4pm
13-10-2023  15:23        85,733,531 04_10_4pm.zip
04-12-2023  16:36               185 04_12_03_05_pm.sql
05-08-2023  17:33       144,122,096 05_08_1PM.zip
05-12-2023  17:47             1,293 05_12_03_05_pm.sql
06-12-2023  17:03             2,829 06_12_03_05_pm.sql
07-12-2023  11:59            16,680 06_12_10_12.ipynb
06-12-2023  10:56            14,637 06_12_10_12_part2.ipynb
16-12-2023  18:13             4,713 07_12_03_05_pm.sql
07-12-2023  11:59            17,005 07_12_10_12AM.ipynb
07-12-2023  14:40            27,657 07_12_12_noon.ipynb
08-04-2023  17:46             6,413 08_04_2023_window functions__damini_04_06.sql
08-05-2023  17:43           453,229 08_05_power bi.pbix
08-11-2022  11:41           412,631 08novresume.pdf
09-04-2023  17:37             2,262 09_damini stored_processor.sql
08-10-2022  12:44               582 1.0.5
04-06-2024  14:37            33,499 1.1230_130.xlsx
04-06-2024  13:54            33,505 1.Mathematical+Functions.xlsx
11-04-2023  14:25       279,467,547 10_04_2023.mp4
16-09-2022  19:48         7,070,153 100-Business-English-Expressions.pdf
23-09-2022  08:41         1,139,062 101-Essays-That-Will-Change-The-Way-You-Think_.pdf
03-01-2023  14:28    <DIR>          1071244354_9761672683050
03-01-2023  14:23            27,403 1071244354_9761672683050.rar
14-12-2022  23:53    <DIR>          1081876154_needhelp
14-12-2022  23:49        16,781,691 1081876154_needhelp.zip
03-04-2023  15:02    <DIR>          10thAprilDeploymentSteps-20230403T093128Z-001
09-06-2023  23:28    <DIR>          10thAprilDeploymentSteps-20230609T175740Z-001
09-06-2023  23:27         1,879,584 10thAprilDeploymentSteps-20230609T175740Z-001.zip
31-03-2023  17:05    <DIR>          10thOctBA-20230331T112251Z-001
02-05-2023  23:02    <DIR>          10thOctBA-20230502T173034Z-001
02-05-2023  23:00         4,290,115 10thOctBA-20230502T173034Z-001.zip
19-03-2023  14:58           136,129 11_03_2023_Saurabh .ipynb
01-04-2023  14:11             7,548 11_04_matplotlib.ipynb
12-12-2023  15:27             6,270 11_12_03_05_pm.sql
12-12-2023  10:56            26,245 11_12_10_12AM.ipynb
12-12-2023  12:23            33,486 11_12_12_noon_part_1.ipynb
04-12-2023  10:44    <DIR>          1-1699437272409_USBDisplay_2.2.7.3
04-12-2023  10:44        39,584,067 1-1699437272409_USBDisplay_2.2.7.3.zip
04-07-2023  12:00            16,100 11AM_04_07.ipynb
13-12-2023  19:36            22,173 12_12_Pythn_basics_06_08.ipynb
07-01-2023  11:15           251,753 1215725943_2151672927494.rar
12-12-2022  21:33             3,972 1236247724_attach-file-1670846640142.zip
03-01-2023  15:27            94,784 1257579810_9101672689580.xlsx
03-01-2023  15:27            94,784 1277482325_7351672689456.xlsx
05-03-2023  17:24    <DIR>          12thSep-20230305T115045Z-001
05-03-2023  17:21         1,800,263 12thSep-20230305T115045Z-001.zip
13-07-2024  18:00           197,894 13_07_Hr_data_analytics.pbix
13-10-2023  15:38            24,342 13_10_power_bi_practice.jpg
17-10-2023  10:39           855,868 13_10_power_bi_practice.pbix
13-10-2023  15:46         5,987,079 13_10_power_bi_practice.pdf
13-10-2023  15:47        17,291,371 13_10_power_bi_practice.pptx
13-12-2023  19:51             9,412 13_12_03_05_pm.sql
18-12-2023  16:45            61,265 13_12_10_12pm.ipynb
03-01-2023  15:27            94,784 132808084_2671672689536.xlsx
03-01-2023  15:29            68,516 1346113162_attach-file-1672689878840.xlsx
14-12-2023  17:09             9,941 14_12_03_05_pm.sql
18-12-2023  16:45           158,114 14_12_12_noon.ipynb
19-12-2023  10:29            95,736 14_12_Pythn_basics_06_08.ipynb
14-03-2023  09:44                63 14_textfile.txt
06-01-2023  08:59         4,894,621 1472359526_2145622_1839731_6302138.docx.pdf
17-02-2024  01:16             5,438 1564534_customer_man_user_account_profile_icon.png
07-01-2023  11:15            40,869 1622747648_4091673022377.PNG
16-06-2022  12:41           821,305 1655303783088.pdf
16-06-2022  12:42           805,584 1655361164152.pdf
24-06-2022  11:57         1,554,236 1655729738530.pdf
22-06-2022  11:00         2,858,697 1655808683836.pdf
22-06-2022  10:01           474,528 1655817362570.pdf
31-07-2022  23:27           194,662 1659268223394.pdf
01-08-2022  12:03           202,563 1659327300591.pdf
19-08-2022  11:56            95,777 1660554784534.pdf
31-08-2022  14:56            76,256 1660633425891.pdf
20-08-2022  13:03           278,174 1660706504763.pdf
18-08-2022  12:25         2,285,675 1660796239124.pdf
20-08-2022  13:03           290,834 1660964997593.pdf
28-08-2022  23:57            84,072 1661491570743.pdf
03-09-2022  11:57        24,347,918 1662176194924.pdf
11-09-2022  19:15         3,089,241 1662895783938.pdf
16-10-2022  19:04            25,278 1665927254292T5LGVZEqHRtY18DM.pdf
02-11-2022  15:29         1,348,909 1667367903949.pdf
24-03-2023  20:17           346,341 1679666303576.pdf
11-10-2023  20:10            34,408 1697035238395WyAqtwm14RdR0r36.pdf
11-10-2023  20:17            26,959 1697035678438ZuVMhzootwhS9VZY.pdf
11-10-2023  20:18            25,911 1697035704347nTpQ2xwqW4vU8dYJ.pdf
17-09-2023  01:01             7,843 16Sep_textbasedproject.ipynb
17-12-2023  11:41            74,038 17_12_10_01_pm_part_1.ipynb
30-12-2023  11:09            25,536 17_12_10_01_pm_part2.ipynb
24-11-2022  10:04           245,499 1733335575_2126730_1816551_6245808.docx.pdf
08-10-2022  23:14    <DIR>          18.3.Plotly.7z (Unzipped Files)-20221008T174315Z-001
08-10-2022  23:13         4,688,447 18.3.Plotly.7z (Unzipped Files)-20221008T174315Z-001.zip
18-12-2023  18:04            10,484 18_12_03_05_pm.sql
10-10-2022  16:40         2,879,041 18_4_Cufflinks_checkpoint.ipynb
24-11-2022  15:10           243,853 1813334027_2126730_1817076_6247183.docx.pdf
30-07-2024  14:21            61,287 1825c07d545cd7779de6f2dfdf38356592d12e4f95a3207462293f2a8cfbb22f_encrypt_signedFinal (1).pdf
30-07-2024  14:21            61,287 1825c07d545cd7779de6f2dfdf38356592d12e4f95a3207462293f2a8cfbb22f_encrypt_signedFinal.pdf
07-01-2023  12:30         4,890,890 1835446948_Updated_solution_06012023.docx.pdf
03-01-2023  14:32    <DIR>          1867855190_9251672678839
03-01-2023  14:23            47,736 1867855190_9251672678839.rar
20-12-2023  18:29            36,701 19_12_06_08.ipynb
19-12-2023  15:09            68,889 19_12_10_12_pm.ipynb
03-01-2023  15:24            17,779 1900425184_attach-file-16726896538021.docx
03-01-2023  15:27            94,784 1925709743_4951672689567.xlsx
07-01-2023  16:26            30,201 1964090971_attach-file-1672220444499.docx
03-01-2023  15:29            63,488 1976883288_attach-file-1672689879136.doc
29-09-2022  05:57         5,227,782 1-deep learning (1).pdf
18-08-2022  17:45         5,227,782 1-deep learning.pdf
19-07-2022  21:09         5,812,051 1-Simple Linearregression.pdf
07-10-2022  21:35           694,907 1st Oct Data Science industry(3-Git ).pdf
10-03-2023  16:06        26,300,953 1st Oct FSDA-20230310T103630Z-001.zip
20-12-2023  18:20            11,002 20_12_03_05_pm.sql
20-12-2023  13:08           165,414 20_12_12_14_pm_part2.ipynb
08-01-2023  13:06            31,186 2009659.docx
11-10-2023  22:44         3,317,648 20231011_222916.jpg
11-10-2023  22:44         3,588,576 20231011_222936.jpg
11-10-2023  22:44         3,530,669 20231011_223005.jpg
11-10-2023  22:44         3,352,405 20231011_223023.jpg
11-10-2023  22:44         3,500,601 20231011_223036.jpg
11-10-2023  22:44         3,435,169 20231011_223049.jpg
11-10-2023  22:44         3,303,889 20231011_223114.jpg

01-01-2024  14:38             7,447 2024.jpeg
01-01-2024  14:41            12,099 20242.jpeg
01-01-2024  14:46            15,420 20243.jpeg
01-01-2024  14:56            14,103 20244.jpeg
03-01-2023  14:23            41,767 2049695533_1501672678817.PNG
03-01-2023  20:53         2,991,850 2050840287_6571672736572.rar
30-11-2022  10:51    <DIR>          2057936858_1521669747194
25-11-2022  20:59           282,615 2064437649_6111669265346 (1).xlsx
25-11-2022  12:53           282,615 2064437649_6111669265346.xlsx
21-03-2023  13:56             5,943 21_03_ruda_utkarsh.sql
21-09-2023  12:57           456,688 21_09_Resume.pdf
26-12-2023  10:45            80,802 21_12_06_08.ipynb
21-12-2023  15:02            46,376 21_12_10_12pm.ipynb
26-11-2022  17:43           207,304 2119999.zip
24-11-2022  10:30    <DIR>          2126730
16-09-2022  19:46         1,477,146 2127.pdf
26-11-2022  17:34    <DIR>          2127053
26-11-2022  17:25        10,955,424 2127053 (2).zip
24-11-2022  12:41           154,637 2127053.zip
28-02-2023  15:05    <DIR>          2129919
29-11-2022  16:40         9,059,733 2129919.zip
03-07-2022  11:53    <DIR>          21stMay-20220702T055745Z-001
30-07-2023  16:12         6,863,802 21stMay-20220702T055745Z-001.zip
24-04-2023  13:01           375,712 22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-04-24-07-31-10.zip
30-08-2023  20:49           114,114 22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-08-30-15-19-02.zip
07-09-2023  10:31    <DIR>          22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-09-07-05-00-53
07-09-2023  10:31           132,147 22b01038ed616ac43165687bedaaee45ee8fbebc93c75e197f48c529c415222e-2023-09-07-05-00-53.zip
03-07-2022  11:53    <DIR>          22ndmay-20220702T055801Z-001
10-09-2022  23:12    <DIR>          23. Django-20220910T174146Z-001
10-09-2022  23:12           635,343 23. Django-20220910T174146Z-001.zip
23-05-2024  15:24           156,762 24_06_sanjay_cv.pdf
24-09-2023  23:54            10,895 24_09_practice.sql
08-06-2024  19:03           270,127 24060800149347SBIN_ChallanReceipt (1).pdf
13-10-2023  13:47           641,619 25_09_power_bi_practice.pbix
26-09-2023  00:19             1,059 25_09_practice.sql
25-12-2022  23:08           402,470 25resume.pdf
07-10-2022  21:35         2,513,681 25th Sept Industry ready 1-DS Project Flow.pdf
26-08-2024  08:58           112,443 26_08_sanjay_cv.pdf
25-09-2023  22:30               576 26_09_Open_Cv and Beautiful_soup.ipynb
27-09-2023  00:50             9,544 26_09_practice.sql
26-12-2023  17:24    <DIR>          26_12_03_05fullstack
26-12-2023  17:25             6,320 26_12_03_05fullstack.zip
26-12-2023  15:38           111,611 26_12_12_14_pm.ipynb
26-11-2022  17:58             9,280 26-11-2022.png
27-09-2023  00:51             9,544 27_09_practice.sql
27-12-2023  19:41            72,489 27_12_06_08.ipynb
27-12-2023  12:22            58,773 27_12_10_12pm.ipynb
27-12-2023  13:53            62,744 27_12_12_14_pm.ipynb
28-07-2023  21:29            24,900 28.ipynb
28-09-2023  01:15            12,033 28_09_practice.sql
29-11-2022  14:00            12,498 28-11-2022.png
03-07-2022  11:53    <DIR>          28thmay-20220702T055846Z-001
30-09-2023  01:00            14,178 29_09_practice.sql
03-07-2024  13:42            58,411 296063ffaa663ca98795717abb70a4feb8e6613832d32c4acc9e096b45ed4874_encrypt_signedFinal.pdf
09-02-2023  12:22           401,917 29resumefinal (1).pdf
09-02-2023  12:28           401,917 29resumefinal (2).pdf
09-02-2023  19:44           401,917 29resumefinal (3).pdf
12-02-2023  12:00           401,917 29resumefinal (4).pdf
29-01-2023  20:16           401,917 29resumefinal.pdf
03-07-2022  11:53    <DIR>          29thMay-20220702T055900Z-001
29-09-2022  05:58         4,936,410 2-Deep Learning-Activation Function,Loss Function,vanishing gradient problems.pdf
19-07-2022  22:15         6,177,864 2-RidgeLassoelasticLogistic.pdf
29-09-2022  06:00         3,811,002 3- Deep Learning optimizers.pdf
31-05-2023  16:29            53,051 30 May.rar
30-07-2023  15:18            23,986 30_07_firoj_tapan.ipynb
13-10-2023  23:41            14,185 30_09_practice.sql
31-12-2023  13:44            94,661 30_31_12_10_01_pm.ipynb
31-05-2024  21:14             5,923 31_05_pratice.sql
31-12-2022  22:15           310,589 31december-2022_production.png
03-01-2023  12:54         1,021,563 322231446_2145949_1838688_6299658.docx.pdf
16-12-2022  09:38         1,088,545 3494407_924284817_5221671127587.pdf
20-07-2022  20:30         4,476,715 3-NaiveBayes&KNN (1).pdf
06-01-2023  13:43    <DIR>          4000_2145811
29-12-2022  13:04             1,014 486285524_report.PNG
06-08-2022  20:04            46,783 48d054d7-9ca9-41a2-af20-6da22f7b1687.pdf
26-11-2022  09:50           371,264 57-Full Manuscript-303-1-10-20210101.pdf
05-09-2023  16:16           115,254 5-sep-23..Matplotlib.ipynb
03-07-2022  11:53    <DIR>          5thJune-20220702T060018Z-001
07-01-2023  11:15            40,869 610424553_8661673022502.PNG
03-01-2023  15:26            94,784 611890008_attach-file-1672689653245.xlsx
08-01-2023  13:05            32,708 6174694_2019475483_ITSecurityofAssetsAuditReport.docx
08-01-2023  13:05            52,373 6174695_773413174_answersheet.docx
30-11-2022  10:10    <DIR>          6202146_557902306_1711667066232
30-11-2022  10:08         4,336,189 6202146_557902306_1711667066232.zip
29-11-2022  17:08           192,888 6213366_724256128_8881667618211.pdf
29-11-2022  17:08           192,888 6213367_42476707_7311667618413.pdf
25-11-2022  10:06           319,905 6214359_1000821664_ISYS40251DerivingBusinessValue (1).docx
08-01-2023  13:04           319,905 6214359_1000821664_ISYS40251DerivingBusinessValue (2).docx
15-11-2022  21:58           319,905 6214359_1000821664_ISYS40251DerivingBusinessValue.docx
19-11-2022  20:37            17,603 6226585_977810161_ForecastingProjectFall20221 (1).docx
26-11-2022  17:33            20,243 6226585_977810161_ForecastingProjectFall20221 (2).docx
19-11-2022  20:03            17,603 6226585_977810161_ForecastingProjectFall20221.docx
26-11-2022  18:03           178,331 6227997_804850198_4311668368487 (1).pdf
25-11-2022  20:54           178,331 6227997_804850198_4311668368487.pdf
15-11-2022  21:59           376,297 6228599_713001643_606D817C-0AE9-4AF8-9679-8AC576.jpeg
24-11-2022  10:35           169,788 6244932_594254105_lab3.pdf
24-11-2022  16:13            63,116 6246945_1997681302_1571669247673 (1).docx
24-11-2022  10:33            63,116 6246945_1997681302_1571669247673.docx
25-11-2022  10:01           172,719 6248251_1610762773_5221669311232.pdf
26-11-2022  12:02            27,462 6248737_15177946_AssignmentRoverPart2.docx
29-11-2022  17:18           156,402 6253046_1015605848_Rawdata-assignment-20221116.zip
29-11-2022  10:49           187,004 6255566_1848008959_6871669689685 (1).rar
29-11-2022  10:49           187,004 6255566_1848008959_6871669689685.rar
30-11-2022  10:16            34,337 6256887_1144032372_4721669744820.docx
30-11-2022  10:31            17,680 6256973_658864227_3561669747930.docx
02-12-2022  09:40    <DIR>          6257614_970114486_CMSC733Assignment5
02-12-2022  09:37            40,181 6257614_970114486_CMSC733Assignment5.zip
02-01-2023  16:47           153,635 6284500_324218519_4231671106208 (1).pdf
02-01-2023  16:46           153,635 6284500_324218519_4231671106208.pdf
29-12-2022  12:08            14,023 6293639_1144537252_task3.docx
29-12-2022  17:33           232,403 6296326_1215288445_9411672312163.pdf
29-12-2022  17:30            57,383 6296343_971359209_6011672312673 (1).docx
29-12-2022  17:34            57,383 6296343_971359209_6011672312673 (2).docx
06-01-2023  14:04            57,383 6296343_971359209_6011672312673 (3).docx
29-12-2022  17:15            57,383 6296343_971359209_6011672312673.docx
30-12-2022  18:05             4,998 6297173_1069742042_9271672401337 (1).rar
30-12-2022  18:04             4,998 6297173_1069742042_9271672401337.rar
30-12-2022  18:07             3,000 6297175_1552145183_2901672401396.rar
02-01-2023  17:05            26,914 6298281_303235459_62978852120552226SCI442Coursew (1).docx
03-01-2023  12:07            26,914 6298281_303235459_62978852120552226SCI442Coursew (2).docx
02-01-2023  16:56            26,914 6298281_303235459_62978852120552226SCI442Coursew.docx
03-01-2023  14:01           143,842 6299068_948091880_5831672665101.png
03-01-2023  14:01           354,285 6299069_207794875_6801672665102.pdf
03-01-2023  15:32            13,303 6299357_465611549_7671672685975.docx
03-01-2023  15:32         5,057,999 6299358_68953781_8531672685976.xlsx
03-01-2023  15:32        50,512,925 6299359_1675536243_3811672685978.xlsx
03-01-2023  15:23            94,784 6299371_175633961_6431672687293.xlsx
03-01-2023  20:50            22,089 6299849_410794984_5291672744220.docx
03-01-2023  20:52           581,082 6299990_898942029_6041672751306.pdf
05-01-2023  16:37           239,959 6301385_1625681581_2191672881498.pdf
07-01-2023  16:25           261,717 6301425_1448130059_7801672890194.docx
07-01-2023  16:25           212,207 6301426_654502130_9391672890196.docx
07-01-2023  16:23       201,617,580 6301722_238167626_4761672913933 (1).docx
05-01-2023  22:18       201,617,580 6301722_238167626_4761672913933.docx
07-01-2023  16:18           168,819 6303202_1793967889_8071673025731.gif
07-01-2023  16:18           179,000 6303203_1296589249_8851673025731.gif
07-01-2023  16:17           208,620 6303204_300042897_4791673025732.gif
07-01-2023  16:17           178,322 6303206_1885821677_5561673025733.gif
07-01-2023  15:18           231,559 6303420_654443766_5141673049427.pdf
03-09-2022  11:53           543,608 6a2d2d74-fd47-4c8e-9305-83c33f35b46f.pdf
03-01-2023  20:53         2,991,850 719257568_2871672743580.rar
15-07-2024  08:46            14,315 7548933_user_interface_moon_half_night_icon.png
15-07-2024  08:45             8,364 7549094_user_interface_moon_half_night_icon.png
07-01-2023  12:31        37,137,379 881577687_marketing_campaign.csv.pdf
02-07-2022  11:30         7,136,886 8-Gradientboosting-kmeanshierarichal.pdf
29-06-2022  17:02         6,328,057 8thJanStats3.pdf
29-06-2022  17:02         6,662,750 9thJanStats4.pdf
08-04-2024  21:17         1,463,552 aadhaar suman.jpg
12-06-2024  10:00           774,053 aadhar front page.zip
06-06-2023  13:31            54,013 abc.pdf
10-06-2023  13:49           261,128 Account_Statement_100323_090623.pdf
10-06-2023  13:52           282,455 Account_Statement_3month.pdf
10-06-2023  13:50           261,128 Account_Statement_last3month.pdf
29-09-2022  05:59         3,253,779 activation function.zip
11-07-2024  13:06            21,390 Advanced+Excel+Analytics+in+Excel (1).xlsx
12-10-2022  21:35            21,390 Advanced+Excel+Analytics+in+Excel.xlsx
27-10-2022  13:15            61,223 AI ENGINEER MATRIX.xlsx
01-01-2024  18:02             6,996 ai.jpeg
16-07-2023  14:46         3,999,366 airbanb.pdf
31-03-2023  18:45             1,746 AirPassengers.csv
08-01-2023  13:06            28,742 annotated bibliography.docx
13-11-2023  16:50             4,894 answere_key_cce.txt
01-12-2023  14:28         5,525,576 AnyDesk (1).exe
04-08-2022  21:13           510,875 aPI.pdf
19-12-2023  13:28               487 api19.py
29-03-2024  13:27            85,789 APic (1).jpg
29-09-2022  06:11         1,416,716 Apple+quarterly+balance+sheet.pdf
29-09-2022  06:11         1,429,366 Apple+quarterly+balance+sheet+1.pdf
13-05-2024  10:58           708,110 AppleStore.csv
31-07-2024  20:06         2,428,871 application (1).pdf
20-07-2024  19:19         2,533,029 application.pdf
04-12-2023  18:37            25,398 apply.docx
10-06-2023  13:53           427,017 Apr'23 (1).pdf
08-06-2023  09:39           427,017 Apr'23.pdf
02-09-2022  17:49    <DIR>          archive
03-09-2022  13:06    <DIR>          archive (1)
03-09-2022  13:05           641,269 archive (1).zip
02-09-2022  17:48         5,732,543 archive.zip
12-12-2022  15:08           524,200 AReM.zip
10-03-2023  18:49         1,103,184 arnaud-jaegers-Al7IoQ74-LU-unsplash.jpg
08-02-2024  18:30               143 asd.html
12-03-2023  14:33    <DIR>          asd.py
31-05-2023  17:05                89 asdf.txt
11-05-2024  13:10           229,915 ash.jpg
10-03-2023  21:49    <DIR>          ASSIGNMENT
29-09-2022  19:54        10,401,953 assignment (2) (2).xlsx
11-04-2024  16:17    <DIR>          Assignment1
11-04-2024  16:16             1,543 Assignment1.zip
13-10-2023  22:10           173,843 Assumptions-of-Linear-Regression.pdf
30-07-2022  22:27           104,846 atlassian-git-cheatsheet.pdf
11-06-2024  15:03           170,946 ATR-17032882.pdf
26-10-2023  12:02           860,651 Aug_sep_salary_slip.pdf
26-10-2023  12:00           431,525 Aug'23 (1).pdf
26-10-2023  12:00           431,525 Aug'23.pdf
08-03-2024  18:58            14,707 avengers.jpeg
20-03-2024  15:16            15,265 avengers1.jpg
19-04-2023  09:58    <DIR>          AWS
21-12-2023  15:02               404 back.py
08-02-2024  18:41            67,646 bag_shopping_client_help_business_support_customer_icon_261688.ico
07-06-2023  11:22           579,043 bank.zip
07-06-2023  11:22           444,572 bank-additional.zip
01-04-2024  21:18            39,818 banner.webp
23-01-2023  22:29           391,059 bas_resume23.pdf
08-01-2023  13:06            15,587 Basics.docx
20-03-2024  15:20            10,496 bhagmbag.jpg
01-12-2022  16:05    <DIR>          Big_Data_Analytics_UZH-master
01-12-2022  16:04           744,774 Big_Data_Analytics_UZH-master.zip
17-12-2022  13:54    <DIR>          book_rating_prediction
17-12-2022  14:45       101,781,720 book_rating_prediction17.zip
27-01-2023  11:24            17,462 Book1.xlsx
17-12-2022  13:44    <DIR>          bookprediction
16-12-2022  13:22         1,032,922 books_model.pkl
16-12-2022  14:01         1,346,128 bostonhousepricing-main.zip
01-12-2023  13:04    <DIR>          Breast-Cancer-Prediction-main
01-12-2023  13:03         1,531,872 Breast-Cancer-Prediction-main.zip
27-06-2023  20:36    <DIR>          BUSINESS
27-06-2023  21:32        97,291,742 BUSINESS (2).zip
25-06-2023  14:14        97,109,862 BUSINESS.zip
11-05-2024  13:11             9,455 c++.jpeg
23-03-2023  19:56           555,360 c76bb6b8-8d0d-42ca-8438-976e438247bf.pdf
20-12-2023  16:01            53,593 car_evaluation (1).csv
20-12-2023  16:01            53,593 car_evaluation (2).csv
04-07-2023  12:14            53,593 car_evaluation.csv
28-03-2024  15:25             5,785 cararra1.jpg
01-12-2023  13:29    <DIR>          Cardio-Monitor-main
01-12-2023  13:29         8,363,144 Cardio-Monitor-main.zip
01-12-2023  13:48         8,400,720 Cardio-Monitor-main_lakshay.zip
01-12-2023  14:19    <DIR>          Cardio-Monitor-main_lakshay12
01-12-2023  13:49         8,400,720 Cardio-Monitor-main_lakshay12.zip
07-10-2022  17:33            26,717 CarPrice_Assignment.csv
28-03-2024  15:25             6,840 carra1.jpg
03-12-2023  17:05             8,616 carreer.jpeg
07-01-2023  13:24    <DIR>          case notes
20-10-2023  19:59            85,789 Casual_Pic.jpg
13-11-2023  19:35            64,758 CCE_papeer.docx
16-10-2022  12:44           808,213 CCI02252019_0005.jpg
16-10-2022  12:46           706,992 CCI02252019_0005-min.jpg
16-10-2022  12:48           655,726 CCI02252019_0005-minedi.jpg
27-04-2023  11:19             5,132 chatgpt.jpeg
01-11-2023  11:01           433,931 ChatGPT_chat.zip
29-12-2023  19:24            67,646 christmas_three_icon_260195.ico
03-04-2023  15:51    <DIR>          chromedriver_win32
09-06-2023  21:49    <DIR>          chromedriver_win32 (1)
09-06-2023  21:47         6,603,303 chromedriver_win32 (1).zip
03-04-2023  15:51         7,117,143 chromedriver_win32.zip
14-04-2023  15:23                57 Class schedule.csv
14-04-2023  15:14            25,600 Class schedule.xls
27-09-2022  15:06    <DIR>          Class_notebooks-20220927T091839Z-001
27-09-2022  14:49         3,661,484 Class_notebooks-20220927T091839Z-001.zip
22-04-2023  16:39             3,516 cleaneddata (1).csv
22-04-2023  16:38             4,007 cleaneddata.csv
29-05-2023  14:39    <DIR>          code
29-05-2023  12:43        42,822,011 code.zip
14-04-2024  15:04         4,032,231 Coffee_Table_Book_MUDRA.pdf
08-06-2023  09:42         1,282,675 combinepdf.pdf
11-05-2024  10:11             4,919 comment.png
19-07-2024  11:00               327 comments.png
12-03-2023  14:34    <DIR>          computer vision
10-09-2023  22:53                 0 computer.txt
03-09-2022  17:55           299,120 conda-cheatsheet (1).pdf
05-06-2023  12:14           299,120 conda-cheatsheet (2).pdf
03-09-2022  17:55           787,695 conda-cheatsheet.pdf
29-01-2023  13:56             1,083 Configuration.xml
19-09-2023  23:07    <DIR>          Course
01-08-2022  14:05         2,434,564 Crop Recommendation System Project.pdf
20-04-2023  20:42         3,014,476 Customer Profitability Sample PBIX.pbix
20-04-2023  20:43         2,906,427 Customer Profitability Sample-no-PV.xlsx
25-05-2023  14:03    <DIR>          cv2
01-01-2024  17:38             9,234 da.jpeg
24-09-2022  21:51    <DIR>          Data
31-03-2024  15:43            12,720 data ana.jpeg
03-12-2023  15:48             7,160 data cleaning.jpeg
07-10-2022  17:17            14,884 Data Dictionary - carprices.xlsx
11-07-2024  13:07             9,666 data.xlsx
24-09-2022  21:50           709,466 Data.zip
22-09-2023  14:17           636,609 Data_Science_certificate.png
10-09-2023  22:50                 0 data10.txt
07-12-2023  16:40                15 data2023.csv
13-12-2023  16:21               328 data2024.csv
10-04-2024  15:06           100,058 dataana.png
11-04-2024  22:06            10,729 dataanal.jpeg
13-03-2023  11:52           379,397 data-analytics iamge.html
12-10-2022  17:54    <DIR>          database.sqlite
18-03-2023  11:34       133,811,040 database.sqlite.zip
31-07-2022  18:17       372,798,464 database1.sqlite
12-10-2022  17:46                 0 database5.sqlite
22-04-2023  16:43             8,347 dataexcel (1).xlsx
22-04-2023  16:42             9,286 dataexcel.xlsx
01-01-2024  17:42             8,039 datagovern.png
03-12-2023  15:04             6,791 datascieneceworkflow.png
13-09-2022  21:40        24,741,696 dataset (1).rar
02-01-2023  15:48            28,209 dataset issue.png
13-09-2022  21:39        24,741,696 dataset.rar
27-04-2023  16:32    <DIR>          data-society-global-terrorism-data
03-06-2024  22:08            22,397 Date-Time+Functions.xlsx
31-03-2023  20:14           118,690 Dax 2.pbix
31-03-2023  18:08           430,086 DAX.pbix
11-10-2022  13:38         2,493,152 Day04-Docker-20221011T080805Z-001.zip
07-01-2023  13:33            31,303 ddddddWRrrrrrrr.png
05-08-2022  11:46         1,569,899 Deep learning (2).pdf
01-08-2022  14:05           378,488 Deep Learning.pdf
12-05-2024  17:57             2,958 delete.png
08-03-2024  21:01                 3 demo.html
26-12-2023  10:45            17,623 demo.ipynb
15-09-2023  23:28                 0 demo1.py
06-12-2022  14:50    <DIR>          Deployement
20-07-2024  19:22            87,277 details.pdf
03-03-2024  11:10             7,895 dhamaal.jpeg
20-03-2024  15:19            11,929 dhol.jpg
27-09-2022  18:35    <DIR>          Diabetes-prediction-project-main
27-09-2022  18:35         1,576,224 Diabetes-prediction-project-main.zip
27-09-2022  18:34           510,271 diabetes-prediction-rfc-model.pkl
16-07-2023  14:46           970,487 diamond price.pdf
08-01-2023  13:06           546,634 Dissertation.pptx
03-12-2023  14:54    <DIR>          Django_notes
25-06-2024  16:06    <DIR>          django_shubham
09-09-2022  21:49    <DIR>          Django-Socialauth-master
09-09-2022  21:49           146,954 Django-Socialauth-master.zip
11-10-2022  12:49    <DIR>          DL_Tensor_Flow.7z (Unzipped Files)-20221011T071416Z-001
11-10-2022  12:44            15,979 DL_Tensor_Flow.7z (Unzipped Files)-20221011T071416Z-001.zip
27-09-2022  15:06    <DIR>          DL1-20220927T091704Z-001

In [261]:
df = pd.read_csv("iris07_09.csv")

In [262]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [263]:
type(df)

pandas.core.frame.DataFrame

In [265]:
df.head(n = 2)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [267]:
df.tail(n = 3)

     sepal_length  sepal_width  petal_length  petal_width    species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [272]:
df.sample(n = 4)

     sepal_length  sepal_width  petal_length  petal_width    species
121           5.6          2.8           4.9          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
31            5.4          3.4           1.5          0.4     setosa
20            5.4          3.4           1.7          0.2     setosa

In [273]:
df.shape

(150, 5)

In [274]:
df.size

750

In [275]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [276]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [277]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [278]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [279]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [281]:
df['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [284]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [285]:
df.species.nunique()

3

In [289]:
df[df.species == 'setosa'].shape

(50, 5)

In [292]:
df.species.value_counts()['versicolor']

50

In [294]:
df['petal_length'].min()

1.0

In [295]:
df.petal_width.max()

2.5

In [296]:
df.sepal_length.sum()

876.5

In [298]:
df['sepal_width'].mean()

3.0540000000000003

In [299]:
# Sorting

In [301]:
df.sort_values(by=['sepal_length'])

     sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [306]:
df.sort_values(by='petal_length', ascending=False, inplace=True)

In [307]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
131           7.9          3.8           6.4          2.0  virginica
..            ...          ...           ...          ...        ...
36            5.5          3.5           1.3          0.2     setosa
35            5.0          3.2           1.2          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa
22            4.6          3.6           1.0          0.2     setosa

[150 rows x 5 columns]

In [316]:
df = df.sort_values(by=['sepal_length', 'sepal_width'], ascending=[False, True])

In [317]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
8             4.4          2.9           1.4          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [321]:
df.sort_index(inplace=True)

In [322]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [323]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [326]:
df.species.apply(len)

0      6
1      6
2      6
3      6
4      6
      ..
145    9
146    9
147    9
148    9
149    9
Name: species, Length: 150, dtype: int64

In [331]:
df.apply(lambda x:x+x)

     sepal_length  sepal_width  petal_length  petal_width             species
0            10.2          7.0           2.8          0.4        setosasetosa
1             9.8          6.0           2.8          0.4        setosasetosa
2             9.4          6.4           2.6          0.4        setosasetosa
3             9.2          6.2           3.0          0.4        setosasetosa
4            10.0          7.2           2.8          0.4        setosasetosa
..            ...          ...           ...          ...                 ...
145          13.4          6.0          10.4          4.6  virginicavirginica
146          12.6          5.0          10.0          3.8  virginicavirginica
147          13.0          6.0          10.4          4.0  virginicavirginica
148          12.4          6.8          10.8          4.6  virginicavirginica
149          11.8          6.0          10.2          3.6  virginicavirginica

[150 rows x 5 columns]

In [332]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [333]:
# Grouping Data Together

In [336]:
df.agg('min')

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [337]:
df.aggregate('min')

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [339]:
df.aggregate(['min', 'max', 'mean', 'median'])

<ipython-input-339-ffcb6e11e7e8>:1: FutureWarning: ['species'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.aggregate(['min', 'max', 'mean', 'median'])

        sepal_length  sepal_width  petal_length  petal_width    species
min         4.300000        2.000      1.000000     0.100000     setosa
max         7.900000        4.400      6.900000     2.500000  virginica
mean        5.843333        3.054      3.758667     1.198667        NaN
median      5.800000        3.000      4.350000     1.300000        NaN

In [343]:
g_obj = df.groupby(by='species')

In [344]:
g_obj

In [345]:
g_obj.min()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [346]:
g_obj.max()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [347]:
g_obj.sum()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [349]:
g_obj.aggregate(['min', 'max', 'sum', 'mean', 'median']).T

species               setosa  versicolor  virginica
sepal_length min       4.300       4.900      4.900
             max       5.800       7.000      7.900
             sum     250.300     296.800    329.400
             mean      5.006       5.936      6.588
             median    5.000       5.900      6.500
sepal_width  min       2.300       2.000      2.200
             max       4.400       3.400      3.800
             sum     170.900     138.500    148.700
             mean      3.418       2.770      2.974
             median    3.400       2.800      3.000
petal_length min       1.000       3.000      4.500
             max       1.900       5.100      6.900
             sum      73.200     213.000    277.600
             mean      1.464       4.260      5.552
             median    1.500       4.350      5.550
petal_width  min       0.100       1.000      1.400
             max       0.600       1.800      2.500
             sum      12.200      66.300    101.300
             mean      0.244       1.326      2.026
             median    0.200       1.300      2.000

In [351]:
g_obj.describe().T

species                setosa  versicolor  virginica
sepal_length count  50.000000   50.000000  50.000000
             mean    5.006000    5.936000   6.588000
             std     0.352490    0.516171   0.635880
             min     4.300000    4.900000   4.900000
             25%     4.800000    5.600000   6.225000
             50%     5.000000    5.900000   6.500000
             75%     5.200000    6.300000   6.900000
             max     5.800000    7.000000   7.900000
sepal_width  count  50.000000   50.000000  50.000000
             mean    3.418000    2.770000   2.974000
             std     0.381024    0.313798   0.322497
             min     2.300000    2.000000   2.200000
             25%     3.125000    2.525000   2.800000
             50%     3.400000    2.800000   3.000000
             75%     3.675000    3.000000   3.175000
             max     4.400000    3.400000   3.800000
petal_length count  50.000000   50.000000  50.000000
             mean    1.464000    4.260000   5.552000
             std     0.173511    0.469911   0.551895
             min     1.000000    3.000000   4.500000
             25%     1.400000    4.000000   5.100000
             50%     1.500000    4.350000   5.550000
             75%     1.575000    4.600000   5.875000
             max     1.900000    5.100000   6.900000
petal_width  count  50.000000   50.000000  50.000000
             mean    0.244000    1.326000   2.026000
             std     0.107210    0.197753   0.274650
             min     0.100000    1.000000   1.400000
             25%     0.200000    1.200000   1.800000
             50%     0.200000    1.300000   2.000000
             75%     0.300000    1.500000   2.300000
             max     0.600000    1.800000   2.500000

In [352]:
g_obj.count()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [353]:
g_obj.min()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [359]:
df[df.species == 'virginica']['petal_width'].min()

1.4

In [360]:
g_obj.sum()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [362]:
# Handling missing Data
# dropna
# fillna

In [363]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [365]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [367]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [375]:
nan_idx = np.random.randint(0,150,20)

In [376]:
nan_idx

array([146,  98, 104,  71, 121,  14, 126, 128,  53,  69, 148,  21, 110,
        60,  93,  88,   8,  53, 100,  14])

In [379]:
df.sepal_width[nan_idx] = np.nan

<ipython-input-379-7d55a73f8176>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sepal_width[nan_idx] = np.nan

In [380]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          NaN           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          NaN           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [381]:
nan_index = np.random.randint(0,140,15)

In [384]:
df['petal_length'][nan_index] = np.nan

<ipython-input-384-257e916c6fae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['petal_length'][nan_index] = np.nan

In [385]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           NaN          0.2     setosa
4             5.0          3.6           NaN          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          NaN           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          NaN           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [386]:
df.isnull().sum()

sepal_length     0
sepal_width     18
petal_length    13
petal_width      0
species          0
dtype: int64

In [387]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           NaN          0.2     setosa
4             5.0          3.6           NaN          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          NaN           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          NaN           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [392]:
df.dropna(axis=1)

     sepal_length  petal_width    species
0             5.1          0.2     setosa
1             4.9          0.2     setosa
2             4.7          0.2     setosa
3             4.6          0.2     setosa
4             5.0          0.2     setosa
..            ...          ...        ...
145           6.7          2.3  virginica
146           6.3          1.9  virginica
147           6.5          2.0  virginica
148           6.2          2.3  virginica
149           5.9          1.8  virginica

[150 rows x 3 columns]

In [393]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           NaN          0.2     setosa
4             5.0          3.6           NaN          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          NaN           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          NaN           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [394]:
df.fillna(value="sanjay")

     sepal_length sepal_width petal_length  petal_width    species
0             5.1         3.5          1.4          0.2     setosa
1             4.9         3.0          1.4          0.2     setosa
2             4.7         3.2          1.3          0.2     setosa
3             4.6         3.1       sanjay          0.2     setosa
4             5.0         3.6       sanjay          0.2     setosa
..            ...         ...          ...          ...        ...
145           6.7         3.0          5.2          2.3  virginica
146           6.3      sanjay          5.0          1.9  virginica
147           6.5         3.0          5.2          2.0  virginica
148           6.2      sanjay          5.4          2.3  virginica
149           5.9         3.0          5.1          1.8  virginica

[150 rows x 5 columns]

In [399]:
np.round(df.petal_length.mean(),1)

3.8

In [403]:
df['petal_length'].fillna(value=np.round(df.petal_length.mean(),1), inplace=True)

In [404]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           3.8          0.2     setosa
4             5.0          3.6           3.8          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          NaN           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          NaN           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [406]:
df.isna().sum()

sepal_length     0
sepal_width     18
petal_length     0
petal_width      0
species          0
dtype: int64

In [412]:
df.sepal_width.fillna(value=4.5, inplace=True)

In [413]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           3.8          0.2     setosa
4             5.0          3.6           3.8          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          4.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          4.5           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [414]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           3.8          0.2     setosa
4             5.0          3.6           3.8          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          4.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          4.5           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [416]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [417]:
# Concat/merging data Frames

In [418]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           3.8          0.2     setosa
4             5.0          3.6           3.8          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          4.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          4.5           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [422]:
new_df = pd.DataFrame(np.random.randint(0,7, size = (10,4)))

In [423]:
new_df

   0  1  2  3
0  0  4  6  3
1  5  6  1  5
2  5  2  5  4
3  6  4  1  3
4  2  1  6  4
5  3  3  0  4
6  2  6  3  2
7  6  3  1  2
8  6  5  1  1
9  6  0  4  3

In [426]:
new_df["species"] = 'tetrapack'

In [427]:
new_df

   0  1  2  3    species
0  0  4  6  3  tetrapack
1  5  6  1  5  tetrapack
2  5  2  5  4  tetrapack
3  6  4  1  3  tetrapack
4  2  1  6  4  tetrapack
5  3  3  0  4  tetrapack
6  2  6  3  2  tetrapack
7  6  3  1  2  tetrapack
8  6  5  1  1  tetrapack
9  6  0  4  3  tetrapack

In [428]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [430]:
new_df.columns = df.columns

In [431]:
new_df

   sepal_length  sepal_width  petal_length  petal_width    species
0             0            4             6            3  tetrapack
1             5            6             1            5  tetrapack
2             5            2             5            4  tetrapack
3             6            4             1            3  tetrapack
4             2            1             6            4  tetrapack
5             3            3             0            4  tetrapack
6             2            6             3            2  tetrapack
7             6            3             1            2  tetrapack
8             6            5             1            1  tetrapack
9             6            0             4            3  tetrapack

In [434]:
v_concat = pd.concat((df,new_df))

In [436]:
v_concat.shape

(160, 5)

In [438]:
h_concat = pd.concat([df, new_df], axis=1)

In [439]:
h_concat.shape

(150, 10)

In [441]:
h_concat.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa,0.0,4.0,6.0,3.0,tetrapack
1,4.9,3.0,1.4,0.2,setosa,5.0,6.0,1.0,5.0,tetrapack
2,4.7,3.2,1.3,0.2,setosa,5.0,2.0,5.0,4.0,tetrapack
3,4.6,3.1,3.8,0.2,setosa,6.0,4.0,1.0,3.0,tetrapack
4,5.0,3.6,3.8,0.2,setosa,2.0,1.0,6.0,4.0,tetrapack

In [442]:
# merging Data Frames

In [443]:
df1 = pd.DataFrame({
    'S_name' : ['Mohit', 'Jatin', 'Prateek', 'Mohit'],
    'CGPA' : [2,4,5,3]
})

In [444]:
df1

    S_name  CGPA
0    Mohit     2
1    Jatin     4
2  Prateek     5
3    Mohit     3

In [446]:
df2 = pd.DataFrame({
    'T_name' : ['Mohit', 'Jatin', 'Prateek', 'Mohit'],
    'CGPA' : [3,6,8,9]
})

In [447]:
df1

    S_name  CGPA
0    Mohit     2
1    Jatin     4
2  Prateek     5
3    Mohit     3

In [448]:
df2

    T_name  CGPA
0    Mohit     3
1    Jatin     6
2  Prateek     8
3    Mohit     9

In [450]:
df1.merge(right=df2, on='CGPA')

  S_name  CGPA T_name
0  Mohit     3  Mohit

In [451]:
df1.merge(right=df2, on='CGPA', how = "inner")

  S_name  CGPA T_name
0  Mohit     3  Mohit

In [452]:
df1.merge(right=df2, on='CGPA', how = "left")

    S_name  CGPA T_name
0    Mohit     2    NaN
1    Jatin     4    NaN
2  Prateek     5    NaN
3    Mohit     3  Mohit

In [453]:
df1.merge(right=df2, on='CGPA', how = "right")

  S_name  CGPA   T_name
0  Mohit     3    Mohit
1    NaN     6    Jatin
2    NaN     8  Prateek
3    NaN     9    Mohit

In [454]:
df1.merge(right=df2, on='CGPA', how = "outer")

    S_name  CGPA   T_name
0    Mohit     2      NaN
1    Jatin     4      NaN
2  Prateek     5      NaN
3    Mohit     3    Mohit
4      NaN     6    Jatin
5      NaN     8  Prateek
6      NaN     9    Mohit

In [456]:
df1.merge(right=df2, how = "cross")

     S_name  CGPA_x   T_name  CGPA_y
0     Mohit       2    Mohit       3
1     Mohit       2    Jatin       6
2     Mohit       2  Prateek       8
3     Mohit       2    Mohit       9
4     Jatin       4    Mohit       3
5     Jatin       4    Jatin       6
6     Jatin       4  Prateek       8
7     Jatin       4    Mohit       9
8   Prateek       5    Mohit       3
9   Prateek       5    Jatin       6
10  Prateek       5  Prateek       8
11  Prateek       5    Mohit       9
12    Mohit       3    Mohit       3
13    Mohit       3    Jatin       6
14    Mohit       3  Prateek       8
15    Mohit       3    Mohit       9

In [457]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           3.8          0.2     setosa
4             5.0          3.6           3.8          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          4.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          4.5           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [458]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           3.8          0.2     setosa
4             5.0          3.6           3.8          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          4.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          4.5           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [462]:
v_concat.to_csv("my_07_09_data.csv", index=False)

In [464]:
v_concat.to_excel("updated_0709.xlsx",sheet_name="P_done" ,index=False)

<ipython-input-464-3e25ee0f03d0>:1: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  v_concat.to_excel("updated_0709.xlsx",sheet_name="P_done" ,index=False)

In [466]:
df_excel = pd.read_excel("updated_0709.xlsx")

In [467]:
df_excel

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           3.8          0.2     setosa
4             5.0          3.6           3.8          0.2     setosa
..            ...          ...           ...          ...        ...
155           3.0          3.0           0.0          4.0  tetrapack
156           2.0          6.0           3.0          2.0  tetrapack
157           6.0          3.0           1.0          2.0  tetrapack
158           6.0          5.0           1.0          1.0  tetrapack
159           6.0          0.0           4.0          3.0  tetrapack

[160 rows x 5 columns]